spring.application.name=api-gateway

server.port=8070

eureka.client.service-url.defaultZone=http://localhost:9007/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


   #routing
   
   
  spring.cloud.gateway.routes[0].id=patient-service
  spring.cloud.gateway.routes[0].uri=http://localhost:8071 
  spring.cloud.gateway.routes[0].predicates[0]=Path=/patient/**
  
  
  
  
  spring.cloud.gateway.routes[1].id=appointment-service
  spring.cloud.gateway.routes[1].uri=http://localhost:8072 
  spring.cloud.gateway.routes[1].predicates[0]=Path=/appointment/**
  
  
  spring.cloud.gateway.routes[2].id=doctor-service
  spring.cloud.gateway.routes[2].uri=http://localhost:8074 
  spring.cloud.gateway.routes[2].predicates[0]=Path=/doctor/**  
  
  
  
  spring.cloud.gateway.routes[3].id=billing-service
  spring.cloud.gateway.routes[3].uri=http://localhost:8075
  spring.cloud.gateway.routes[3].predicates[0]=Path=/billing/**  
  
  
  
  
  
  spring.cloud.gateway.routes[4].id=prescription-service
  spring.cloud.gateway.routes[4].uri=http://localhost:8076 
  spring.cloud.gateway.routes[4].predicates[0]=Path=/prescription/**  
  
  
  spring.cloud.gateway.routes[5].id=lab-service
  spring.cloud.gateway.routes[5].uri=http://localhost:8077 
  spring.cloud.gateway.routes[5].predicates[0]=Path=/lab/**  
  
   spring.cloud.gateway.routes[6].id=dashboard-service
  spring.cloud.gateway.routes[6].uri=http://localhost:8078 
  spring.cloud.gateway.routes[6].predicates[0]=Path=/dashboard/** 
  
  
  spring.cloud.gateway.routes[7].id=timeline-service
  spring.cloud.gateway.routes[7].uri=http://localhost:8079
  spring.cloud.gateway.routes[7].predicates[0]=Path=/timeline/**
  
 # ===========================
# Swagger API Docs Routes
# ===========================

spring.cloud.gateway.routes[8].id=doctor-docs
spring.cloud.gateway.routes[8].uri=http://localhost:8074
spring.cloud.gateway.routes[8].predicates[0]=Path=/v3/api-docs/doctor
spring.cloud.gateway.routes[8].filters[0]=RewritePath=/v3/api-docs/doctor,/v3/api-docs

spring.cloud.gateway.routes[9].id=patient-docs
spring.cloud.gateway.routes[9].uri=http://localhost:8071
spring.cloud.gateway.routes[9].predicates[0]=Path=/v3/api-docs/patient
spring.cloud.gateway.routes[9].filters[0]=RewritePath=/v3/api-docs/patient,/v3/api-docs

spring.cloud.gateway.routes[10].id=appointment-docs
spring.cloud.gateway.routes[10].uri=http://localhost:8072
spring.cloud.gateway.routes[10].predicates[0]=Path=/v3/api-docs/appointment
spring.cloud.gateway.routes[10].filters[0]=RewritePath=/v3/api-docs/appointment,/v3/api-docs


spring.cloud.gateway.routes[11].id=billing-doc
spring.cloud.gateway.routes[11].uri=http://localhost:8075
spring.cloud.gateway.routes[11].predicates[0]=Path=/v3/api-docs/billing
spring.cloud.gateway.routes[11].filters[0]=RewritePath=/v3/api-docs/billing,/v3/api-docs


spring.cloud.gateway.routes[12].id=prescription-docs
spring.cloud.gateway.routes[12].uri=http://localhost:8076
spring.cloud.gateway.routes[12].predicates[0]=Path=/v3/api-docs/prescription
spring.cloud.gateway.routes[12].filters[0]=RewritePath=/v3/api-docs/prescription,/v3/api-docs


spring.cloud.gateway.routes[13].id=lab-docs
spring.cloud.gateway.routes[13].uri=http://localhost:8077
spring.cloud.gateway.routes[13].predicates[0]=Path=/v3/api-docs/lab
spring.cloud.gateway.routes[13].filters[0]=RewritePath=/v3/api-docs/lab,/v3/api-docs


spring.cloud.gateway.routes[14].id=dashboard-docs
spring.cloud.gateway.routes[14].uri=http://localhost:8078
spring.cloud.gateway.routes[14].predicates[0]=Path=/v3/api-docs/dashboard
spring.cloud.gateway.routes[14].filters[0]=RewritePath=/v3/api-docs/dashboard,/v3/api-docs


spring.cloud.gateway.routes[15].id=timeline-docs
spring.cloud.gateway.routes[15].uri=http://localhost:8079
spring.cloud.gateway.routes[15].predicates[0]=Path=/v3/api-docs/timeline
spring.cloud.gateway.routes[15].filters[0]=RewritePath=/v3/api-docs/timeline,/v3/api-docs





# ===========================
# Swagger UI Dropdown
# ===========================

springdoc.swagger-ui.urls[0].name=Patient Service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/patient

springdoc.swagger-ui.urls[1].name=Appointment Service
springdoc.swagger-ui.urls[1].url=/v3/api-docs/appointment

springdoc.swagger-ui.urls[2].name=Doctor Service
springdoc.swagger-ui.urls[2].url=/v3/api-docs/doctor

springdoc.swagger-ui.urls[3].name=Billing service
springdoc.swagger-ui.urls[3].url=/v3/api-docs/billing

springdoc.swagger-ui.urls[4].name=Prescription-service
springdoc.swagger-ui.urls[4].url=/v3/api-docs/prescription

springdoc.swagger-ui.urls[5].name=Lab service
springdoc.swagger-ui.urls[5].url=/v3/api-docs/lab

springdoc.swagger-ui.urls[6].name=Dashboard service
springdoc.swagger-ui.urls[6].url=/v3/api-docs/dashboard


springdoc.swagger-ui.urls[7].name=Timeline service
springdoc.swagger-ui.urls[7].url=/v3/api-docs/timeline

# ===========================
# Global CORS Configuration
# ===========================
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*